apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-shake-migration
  namespace: redis-shake-migration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-shake-migration
  template:
    metadata:
      labels:
        app: redis-shake-migration
    spec:
      containers:
      - name: redis-shake-migration
        image: hmx098/redis-shake:v4.3.1 # Replace with your container image
        # command: ["./redis-shake"]
        # args: ["/app/shake.toml"]
        command: ["/bin/sh"]
        args: ["-c", " sleep infinity"]
        volumeMounts:
        - name: config-volume
          mountPath: /app/shake.toml
      volumes:
      - name: config-volume
        configMap:
          name: redis-shake-migration-config
