apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dragonfly-operator
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/harsh098/redis-ha-labs.git
    path: argocd/dev/dragonfly-operator  # Update for stage/prod
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true