apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-shake-migration
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: redis-shake-migration
  project: default
  source:
    repoURL: https://github.com/harsh098/redis-ha-labs.git
    path: argocd/dev/redis-shake-migration  # Update for stage/prod
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true