name: Provision Kubernetes Cluster [PROD]

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths: ["terraform/environment/prod/**"]
    types:  ["closed"]



permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  create_infra:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    env:
      TF_LOG: INFO
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      TF_VAR_environment: "production"
      TF_VAR_cluster_name: "redis-migration"
      TF_VAR_vpc_cidr: "10.1.0.0/16"
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/terraform/dev
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE}}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-K8S-cluster

      - name: Checkout repository
        uses: actions/checkout@v1
 
      - name: Setup Terraform
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install -y terraform

      - name: Terraform Init
        id: init
        run: terraform init 
          
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color 
      
      - name: Terraform Apply
        id: apply
        run: |
          terraform plan -no-color 
          terraform apply -auto-approve